name: Tests

on:
  workflow_call:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install uv
          uv pip install --system -r requirements-dev.txt

      - name: Check formatting
        run: ruff format --check
        working-directory: attribution

      - name: Lint source
        run: ruff check
        working-directory: attribution

      - name: Unit test
        run: python -m pytest tests/unit

      - name: Integration test
        run: python -m pytest tests/integration
